/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#0f5238",
        "primary-container": "#2d6a4f",
        "on-primary": "#ffffff",
        "on-primary-container": "#a8e7c5",
        "primary-fixed": "#b1f0ce",
        "primary-fixed-dim": "#95d4b3",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#0e5138",
        "inverse-primary": "#95d4b3",

        secondary: "#00696c",
        "secondary-container": "#8ff3f6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007073",
        "secondary-fixed": "#8ff3f6",
        "secondary-fixed-dim": "#72d6da",
        "on-secondary-fixed": "#002021",
        "on-secondary-fixed-variant": "#004f52",

        tertiary: "#134b74",
        "tertiary-container": "#32638d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bfddff",
        "tertiary-fixed": "#cfe5ff",
        "tertiary-fixed-dim": "#9ccbfb",
        "on-tertiary-fixed": "#001d33",
        "on-tertiary-fixed-variant": "#124a73",

        background: "#f8fafb",
        "on-background": "#191c1d",
        surface: "#f8fafb",
        "on-surface": "#191c1d",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f5",
        "surface-container": "#eceeef",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#404943",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "surface-tint": "#2c694e",

        outline: "#707973",
        "outline-variant": "#bfc9c1",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        botanical: {
          dark: "#354f2e",
          base: "#3b5735",
          mid: "#44633b",
          light: "#527947",
        },
        emerald: {
          accent: "#00c875",
          glow: "#00c371",
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        gutter: "24px",
        lg: "48px",
        xl: "80px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-sm": ["'Hanken Grotesk'", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(15, 82, 56, 0.06)",
        "glass-elevated": "0 12px 40px 0 rgba(15, 82, 56, 0.12)",
        "emerald-glow": "0 4px 20px rgba(0, 200, 117, 0.4)",
      }
    },
  },
  plugins: [],
}
